version: "3.2"
services:
  classandra:
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.dmz != true
      mode: global    
      resources:
        limits:
          memory: 190M
        reservations:
          memory: 76M
    entrypoint:
    - "sh"
    - "-c"
    - export CASSANDRA_SEEDS=$$(nrOfTasks=`getent hosts tasks.cassandra | wc -l` ;
      many=`getent hosts tasks.cassandra | awk '{print $$1}' | sed "/$$(hostname --ip-address)/d"
      | paste -d, -s -` ; printf '%s' $$( [ $${nrOfTasks} -gt 1 ] && echo $${many} ||
      echo "$$(hostname --ip-address)" )) ; /docker-entrypoint.sh cassandra -f
    environment:
      HEAP_NEWSIZE: 12M
      MAX_HEAP_SIZE: 64M
    image: cassandra
    networks:
      classandra:
networks:
  classandra:
