version: "3.2"

networks:
  dgraph:


services:
  zero:
    image: dgraph/dgraph:master
    volumes:
      - vgraphzero:/dgraph
    ports:
      - 6080:6080   # http /status
      - 5080:5080
    networks:
      - dgraph
    restart: on-failure  
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.dmz != true
    command: dgraph zero --port_offset -2000 --my=zero:5080 --bindall=true --replicas 3 --idx=1
    

  servera:
    image: dgraph/dgraph:master
    hostname: servera
    volumes:
      - vgrapha:/dgraph
    ports:
      - 8180:8080
      - 9180:9080
    networks:
      dgraph:
    restart: on-failure
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.dmz != true
    command: dgraph server --my=servera:7080 --memory_mb=2048 --zero=zero:5080 --bindall=true --idx=2


  serverb: 
    image: dgraph/dgraph:master
    hostname: serverb
    volumes:
      - vgraphb:/dgraph
    ports:    
      - 8280:8080
      - 9280:9080
    networks:
      - dgraph
    restart: on-failure
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.dmz != true
    command: dgraph server --my=serverb:7080 --memory_mb=2048 --zero=zero:5080 --bindall=true --idx=3


  serverc: 
    image: dgraph/dgraph:master
    hostname: serverc
    volumes:
      - vgraphc:/dgraph
    ports:   
      - 8380:8080
      - 9380:9080
    networks:
      - dgraph
    restart: on-failure
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.dmz != true
    command: dgraph server --my=serverc:7080 --memory_mb=2048 --zero=zero:5080 --bindall=true --idx=4
    


  serverui:
    image: dgraph/dgraph:master
    hostname: serverui
    ports:
      - 8481:8081
    networks:
      - dgraph
    restart: on-failure
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.dmz != true
    command: dgraph-ratel -addr servera:8180 
    
    
volumes:
  vgraphzero:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/data/volumes/vgraphzero  
  vgrapha:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/data/volumes/vgrapha  
  vgraphb:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/data/volumes/vgraphb  
  vgraphc:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/data/volumes/vgraphc      
